version: '3.4'
services:
    database:
        image: 'mongo'
        container_name: 'mongo_db'
        environment: 
            - MONGO_INITDB_DATABASE=mongo_store
            - MONGO_INITDB_USERNAME=adam
            - MONGO_INITDB_PASSWORD=password
        volumes: 
            - ./mongo-volume:/data/db
        ports: 
            - '27017-27019:27017-27019'